services:
  backend:
    build: ./backend
    volumes:
      - ./frontend/images:/frontend/images
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/images:/usr/share/nginx/html/images
    ports:
      - "8080:80"
